#!/usr/bin/env bash
# Transfers a file from Holberton's client to another.
#
#  Accepts four parameters only:
#     The path to the file to be transferred.
#     The IP of the server to transfer the file to.
#     The username that scp connects with.
#     The path to the SSH private key that scp uses.

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
# assigning parameters to variables

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/

# checking for transfer status
#  this is not part of the task — jx optional
if [ $? -eq 0 ]
then
	echo "Transfer Scuccesfull"
else
	echo "Transfee error, Try again"
fi
