#!/usr/bin/env bash
# Script that installs nginx server and redirects to new address "/redirect_me"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Alx School" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://github.com/zuriel0001/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
