#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
#
# Configure Nginx so that its HTTP response contains
# • A custom header
# • Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 311195-web-01 34.207.189.180:80 check\n\tserver 311195-web-02 54.172.84.52:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
