#!/usr/bin/env bash
# This script displays the contents of the file `/etc/passwd`.
# Only the username, user id, and user home directory path will be displayed

myfile="/etc/passwd"
while IFS= read -r line; do
  echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
