#!/usr/bin/env bash
# This script loops from 10 times.
# On the 4th loop iteration, it dislpay bad luck
# It displays good luck for the 8th loop iteration
# displays Best School for all the other iterations
i="0"
while [ $i -lt 10 ]
do
if [ $i -eq 3 ];
then
    echo "bad luck"
elif [ $i -eq 7 ];
then
    echo "good luck"
else
    echo "Best School"
fi
i=$((i+1))
done
