#!/bin/env bash
###########################################################
# Script: superstitious_numbers.sh
# Description: Displays numbers from 1 to 20 and shows
# specific messages for the 4th, 9th, and 17th loop iterations.
# Author: Your Name
# Date: July 27, 2023
###########################################################
count=1
while [ $count -le 20 ]
do
  case $count in
    4)
      echo "$count and then bad luck from China"
      ;;
    9)
      echo "$count and then bad luck from Japan"
      ;;
    17)
      echo "$count and then bad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  ((count++))
done
