#!/bin/env bash

#########################################
# Script: hours_and_minutes.sh
# Displays hours from 0 to 12 and minutes
# from 1 to 59 for each hour.
# Author: zuriel001
# Date: July 27, 2023
#########################################

h="0"
while [ $h -le 12 ]
do
echo "Hour: $h"
minute="1"
while [ $minute -le 59 ]
do
echo "$minute"
minute=$((minute+1))
done
h=$((h+1))
done
