#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
#  display hours from 0 to 12
#  display minutes from 1 to 59

i="0"
while [ $i -le 12 ]
do
echo "Hour: $i"
minute="1"
while [ $minute -le 59 ]
do
echo "$minute"
minute=$((minute+1))
done
i=$((i+1))
done
