#!/usr/bin/env bash
# Script to run Apache on the holbertonschool/265-0 Docker container

# Update package repositories and install Apache and PHP using sudo
sudo apt-get update
sudo apt-get install -y apache2 php

# Configuring Apache to serve "Hello Holberton"
echo "ServerName localhost" | sudo tee -a /etc/apache2/apache2.conf
echo "<?php echo 'Hello Holberton'; ?>" | sudo tee /var/www/html/index.php

# Start Apache
sudo service apache2 start

# Keep the script running to keep the container running
tail -f /dev/null
